version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
    schedule:
      day: sunday
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    # Disable all pull requests for npm dependencies in docs directory
    open-pull-requests-limit: 0