services:
  base: &base
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    user: ${CURRENT_UID}
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: .
    depends_on:
      - postgres
    volumes:
      - ./server:/app/server

  server:
    <<: *base
    ports:
      - '3000:3000'
    command: python3 -m server

  ishell:
    <<: *base
    command: ipython

  postgres:
    image: postgres:11.22-alpine@sha256:33a78858869c44785eee197a60cf281c5c80376bb725992f092ec5e7e072f3de
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
