run:
  tests: false
  go: 1.18

linters:
  enable-all: true
  disable:
    - typecheck
    - gomoddirectives
    - containedctx
    - gochecknoglobals
    - goimports
    - funlen
    - godox
    - maligned
    - goerr113
    - exhaustivestruct
    - wrapcheck
    - prealloc # enable it sometimes
    - wsl
    - ifshort
    - unparam
    - cyclop
    - gocyclo
    - gocognit
    - tagliatelle
    - nestif
    - nlreturn

linters-settings:
  gomnd:
    settings:
      mnd:
        checks: case,condition,return
  lll:
    line-length: 120
  varnamelen:
    min-name-length: 1

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: set\.go
      linters:
      - typecheck
