run:
  tests: false
  go: "1.23"

linters:
  enable-all: true
  disable:
    - typecheck
    - gomoddirectives
    - containedctx
    - gochecknoglobals
    - goimports
    - funlen
    - godox
    - maligned
    - goerr113
    - exhaustivestruct
    - wrapcheck
    - prealloc # enable it sometimes
    - wsl
    - ifshort
    - unparam
    - cyclop
    - gocyclo
    - gocognit
    - tagliatelle
    - nestif
    - nlreturn
    - goprintffuncname
    - exhaustruct
    - wastedassign
    - nilnil
    - recvcheck
    - musttag
    - mnd
    - lll
    - gocritic
    - forcetypeassert
    - exhaustive
    - depguard
    - revive
    - gosec
    - copyloopvar

linters-settings:
  lll:
    line-length: 120
  varnamelen:
    min-name-length: 1

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: set\.go
      linters:
      - typecheck
