version: "2"
run:
  go: "1.26"
  tests: false
linters:
  default: all
  disable:
    - goconst
    - containedctx
    - copyloopvar
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - funcorder
    - gochecknoglobals
    - gocognit
    - gocritic
    - gocyclo
    - godoclint
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - importas
    - lll
    - mnd
    - musttag
    - nestif
    - nilnil
    - noctx
    - noinlineerr
    - nlreturn
    - prealloc
    - recvcheck
    - revive
    - tagliatelle
    - unparam
    - wastedassign
    - wrapcheck
    - whitespace
    - wsl
  settings:
    lll:
      line-length: 120
    varnamelen:
      min-name-length: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
