version: 2
project_name: lets

before:
  hooks:
    - go mod tidy

release:
  prerelease: auto

builds:
  - id: darwin-amd64
    main: .
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: darwin-arm64
    main: .
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: linux-amd64
    main: .
    binary: golang-cross
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
- formats: [tar.gz]
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else if eq .Arch "darwin" }}Darwin
    {{- else if eq .Arch "linux" }}Linux
    {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: lets
    description: "CLI task runner for productive developers - a better alternative to make"
    homepage: "https://lets-cli.org/"
    license: "MIT"
    repository:
      owner: lets-cli
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula

aurs:
  - name: lets-bin
    homepage: "https://lets-cli.org/"
    description: "CLI task runner for productive developers - a better alternative to make"
    license: "MIT"
    maintainers:
      - 'Kindritskiy Maksym <kindritskiy.m@gmail.com>'
    contributors:
      - "Luis Martinez <luis dot martinez at disroot dot org>"
    private_key: '{{ .Env.AUR_GITHUB_TOKEN }}'
    git_url: 'ssh://aur@aur.archlinux.org/lets-bin.git'
    package: |-
      install -Dm755 "./lets-bin" "${pkgdir}/usr/bin/lets"
    commit_author:
      name: 'Github Action Bot'
      email: kindritskiy.m@gmail.com

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
