project_name: lets

before:
  hooks:
    - go mod tidy

release:
  prerelease: auto

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: linux
      goarch: arm64
  ldflags:
    - -X main.version={{.Version}}

archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else if eq .Arch "darwin" }}Darwin
    {{- else if eq .Arch "linux" }}Linux
    {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: lets
    description: "CLI task runner for productive developers - a better alternative to make"
    homepage: "https://lets-cli.org/"
    license: "MIT"
    repository:
      owner: lets-cli
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula

aurs:
  - name: lets-bin
    homepage: "https://lets-cli.org/"
    description: "CLI task runner for productive developers - a better alternative to make"
    license: "MIT"
    maintainers:
      - 'Kindritskiy Maksym <kindritskiy.m@gmail.com>'
    contributors:
      - "Luis Martinez <luis dot martinez at disroot dot org>"
    private_key: '{{ .Env.AUR_GITHUB_TOKEN }}'
    git_url: 'ssh://aur@aur.archlinux.org/lets-bin.git'
    package: |-
      install -Dm755 "./lets-bin" "${pkgdir}/usr/bin/lets"
    commit_author:
      name: 'Github Action Bot'
      email: kindritskiy.m@gmail.com

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
