before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
