project_name: lets

before:
  hooks:
    - go mod tidy

release:
  prerelease: auto

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: linux
      goarch: arm64
  ldflags:
    - -X main.version={{.Version}}

archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

brews:
  - name: lets
    description: "CLI task runner for productive developers - a better alternative to make"
    homepage: "https://lets-cli.org/"
    license: "MIT"
    tap:
      owner: lets-cli
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
