env:
  DOCKER_BUILDKIT: "1"

commands:
  build-lets-image:
    description: Build lets docker image
    cmd: docker build -t lets -f docker/Dockerfile .

  build-lint-image:
    description: Build lets lint docker image
    cmd: docker build -t lets-lint -f docker/lint.Dockerfile .
