version: '3.7'

services:
  base: &base
    image: lets
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  staticheck:
    <<: *base
    command: staticcheck ./...

  test:
    <<: *base
    command: go test ./... -v
