version: '3.7'

services:
  base: &base
    image: lets
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  lint:
    image: lets-lint
    working_dir: /app
    user: ${CURRENT_UID}
    volumes:
      - ./:/app
    entrypoint: golangci-lint run -v -c .golangci.yaml --fix

  test:
    <<: *base
    environment:
      LETS_CONFIG_DIR: ..
    entrypoint: gotestsum --format testname -- ./... -coverprofile=coverage.out

  test-bats:
    <<: *base
    environment:
      NO_COLOR: 1
      BATS_UTILS_PATH: /bats
    command:
      - bash
      - -c
      - |
        go build -o /usr/bin/lets *.go
        if [[ -n "${LETSOPT_TEST}" ]]; then
          bats tests/"${LETSOPT_TEST}" ${LETSOPT_OPTS}
        else
          bats tests ${LETSOPT_OPTS}
        fi
