version: '3.7'

services:
  base: &base
    image: lets
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  lint:
    image: lets-lint
    working_dir: /app
    user: ${CURRENT_UID}
    volumes:
      - ./:/app
    entrypoint: golangci-lint run -v -c .golangci.yaml --fix

  test:
    <<: *base
    environment:
      LETS_CONFIG_DIR: ..
    entrypoint: [go, test, ./..., -v, -coverprofile=coverage.out]

  test-bats:
    <<: *base
    environment:
      LETS_NO_COLOR_OUTPUT: 1
    command: |
      bash -c '
        go build -o /usr/bin/lets *.go
        if [[ -n "${LETSOPT_TEST}" ]]; then
          bats tests/"${LETSOPT_TEST}"
        else
          bats tests
        fi
      '
