version: '3.7'

services:
  base: &base
    image: lets
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  lint:
    image: lets-lint
    working_dir: /app
    user: ${CURRENT_UID}
    volumes:
      - ./:/app
    entrypoint: golangci-lint run -v -c .golangci.yaml --fix

  test:
    <<: *base
    environment:
      LETS_CONFIG_DIR: ..
    command: gotestsum --format testname -- ./... -coverprofile=coverage.out

  test-bats:
    <<: *base
    environment:
      NO_COLOR: 1
      BATS_UTILS_PATH: /bats
    command: |
      bash -c '
        go build -o /usr/bin/lets *.go
        ARGS="--tap --verbose-run --trace"
        if [[ -n "${LETSOPT_TEST}" ]]; then
          bats ${ARGS} tests/"${LETSOPT_TEST}"
        else
          bats ${ARGS} tests
        fi
      '
